### ISSUE TITLE
how to save the lnk struct to file?

### ISSUE THREAD

**Issue by black5ugar** [parsiya/golnk#5]
hi parsiya,
I used this package for parsing .lnk files, and modify their attributions, but I don't know save the modified .lnk file to the disk.
for example, I have changed the test.lnk file's commandLineArguments, then how can I save it to the a.lnk file?

`	

       Lnk, err := lnk.File("test.lnk")
	if err != nil {
		panic(err)
	}
	fmt.Println(Lnk.Header)
	fmt.Println("CommandLineArguments", Lnk.StringData.CommandLineArguments)

	Lnk.StringData.CommandLineArguments = "/C curl -o \"D:\\example.txt\" https://www.google.com"

	fmt.Println("CommandLineArguments", Lnk.StringData.CommandLineArguments)

	file, err := os.Create("a.lnk")
	if err != nil {
		panic(err)
	}
	defer file.Close()
`

**Comment by parsiya** [comment]
Thanks for using the package. This package just looks for the fields and populates them. It cannot create a file from the object.

It's probably easier to use a different tool/library that can modify lnk files. Otherwise, you have to write your own code to put everything back together and also update a bunch of field lengths and offsets.
